(global-set-key (kbd "M-m")          'magit-status)
(global-set-key (kbd "M-q")          'clipboard-kill-region)
(global-set-key (kbd "M-j")          'clipboard-kill-ring-save)
(global-set-key (kbd "M-k")          'clipboard-yank)
(global-set-key (kbd "C-1")          'show-file-name)
(global-set-key (kbd "C-r")          'remove-dos-eol)
(global-set-key (kbd "M-k")          'yank)
(global-set-key (kbd "M-j")          'kill-ring-save)
(global-set-key (kbd "C-l")          'goto-line)
(global-set-key (kbd "C-=")          'er/expand-region)
(global-set-key (kbd "M-<up>")       'buf-move-up)
(global-set-key (kbd "M-<down>")     'buf-move-down)
(global-set-key (kbd "M-<left>")     'buf-move-left)
(global-set-key (kbd "M-<right>")    'buf-move-right)
(global-set-key (kbd "C-c <up>")     'windmove-up)
(global-set-key (kbd "C-c <down>")   'windmove-down)
(global-set-key (kbd "C-c <left>")   'windmove-left)
(global-set-key (kbd "C-c <right>")  'windmove-right)
(global-set-key (kbd "C-e")          'eval-region)
(global-set-key (kbd "C-z")          'scroll-up-command)
(global-set-key (kbd "C-v")          'scroll-down-command)
(global-set-key (kbd "C-x p")        'package-list-packages)
(global-set-key (kbd "C-M-d")        'dired)
;;(global-set-key (kbd "M-m")          'magit-status)
(global-set-key (kbd "M-f")          'turn-window-into-frame)
(global-set-key (kbd "C-^")          'ddliu-emms-player-mplayer-volume-up)
(global-set-key (kbd "C-6")          'ddliu-emms-player-mplayer-volume-down)
(global-set-key (kbd "M-t")          'helm-for-files)
(global-set-key (kbd "C-c C-u")      'uncomment-region)
(global-set-key (kbd "M-c")          'auto-complete)
;;(global-set-key (kbd "C-x r")        'recompile-init-file)
(global-set-key (kbd "C-c o")        'ibuffer-do-sort-by-major-mode)
(global-set-key (kbd "C-S-r")        'revert-buffer)
(global-set-key (kbd "C-<right>")    'end-of-line)
(global-set-key (kbd "C-<left>")     'beginning-of-line)
(global-set-key (kbd "C-c c")        'comment-region)
(global-set-key (kbd "C-c u")        'uncomment-region)
(global-set-key (kbd "C-x k")        'kill-this-buffer)
;;(define-key php-mode-map (kbd "C-c C-y") 'yas/create-php-snippet)
